[project]
name = "watermark-remover-web"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
    "numpy==1.21.6",
    "opencv-python==4.5.5.64",
    "easyocr==1.4.1",
    "onnxruntime==1.10.0",
    "Pillow==8.2.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
