[project]
name = "watermark-remover-web"
version = "0.0.0"
description = "Watermark remover web application"
authors = ["LandolX <your-email@example.com>"]
requires-python = "^3.9"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

